"""
Shared graph state definition.

RAGState is a TypedDict that flows through every node in the LangGraph pipeline.
Keeping it in its own module prevents circular imports between graph.py and
the individual node modules.

Field descriptions:
    chat_history      : Prior conversation turns (list of {role, content} dicts).
    user_query        : The raw question submitted by the user.
    sub_queries       : Decomposed sub-questions generated by the analyzer node.
    current_query     : The active search query (may be rewritten by the rewriter).
    retrieved_chunks  : Candidate document chunks returned by the retriever.
    attempts          : Number of retrieval attempts made so far.
    response          : Final answer text produced by the synthesizer.
    citations         : List of retrieved chunks used as sources in the answer.
    rejected          : True when the query is out of academic scope.
    enough            : True when the retriever found sufficient chunks to synthesize.
"""

from typing import List, TypedDict


class RAGState(TypedDict, total=False):
    """Mutable state dict passed between all nodes in the LangGraph pipeline."""

    chat_history: List[dict]       # previous turns for multi-turn conversations
    user_query: str                # original user question (never modified)
    sub_queries: List[str]         # decomposed sub-queries from the analyzer
    current_query: str             # active search query (rewriter may update this)
    retrieved_chunks: List[dict]   # chunks returned by the retriever node
    attempts: int                  # retrieval attempt counter
    response: str                  # final synthesized answer
    citations: List[dict]          # source chunks cited in the answer
    rejected: bool                 # True → query was out of scope; graph ends early
    enough: bool                   # True → retriever found sufficient context
